CREATE TABLE IF NOT EXISTS categories (id INTEGER PRIMARY KEY AUTOINCREMENT, name TEXT NOT NULL UNIQUE);
INSERT OR IGNORE INTO categories(name) SELECT DISTINCT category FROM products;
ALTER TABLE products ADD COLUMN category_id INTEGER REFERENCES categories(id);
UPDATE products SET category_id = (SELECT id FROM categories WHERE categories.name = products.category);
CREATE INDEX IF NOT EXISTS idx_products_category ON products(category_id);
CREATE INDEX IF NOT EXISTS idx_cart_user_product ON cart_items(user_id, product_id);
CREATE INDEX IF NOT EXISTS idx_order_items_product ON order_items(product_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_created ON orders(user_id, created_at);
CREATE TABLE order_items_new (id INTEGER PRIMARY KEY AUTOINCREMENT, order_id INTEGER NOT NULL REFERENCES orders(id) ON DELETE CASCADE, product_id INTEGER NOT NULL REFERENCES products(id), qty INTEGER NOT NULL CHECK (qty BETWEEN 1 AND 99), price INTEGER NOT NULL);
INSERT INTO order_items_new(id,order_id,product_id,qty,price) SELECT id,order_id,product_id,qty,price FROM order_items;
DROP TABLE order_items;
ALTER TABLE order_items_new RENAME TO order_items;
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);
